### ISSUE TITLE
Do you have to have a graphics card to use DeepMicroClass?

### ISSUE THREAD

**Issue by 1023011930** [chengsly/DeepMicroClass#11]
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx
**I found the following error reported when running the test data**
**It would be very helpful to have your guidance, thanks!**

**Comment by 1023011930** [comment]
**DeepMicroClass predict --input M8_corrected_contig_NC_clean.fa --output_dir M8_DeepMicroClass --device cpu**

**Comment by tianqitang1** [comment]
We've updated the package and it should work with CPU now, please run `pip install --upgrade DeepMicroClass` and try again, thanks!
