### ISSUE TITLE
 User Error with DeepMicroClass CPU Mode

### ISSUE THREAD

**Issue by jwilliams648** [chengsly/DeepMicroClass#12]
Good day, 

I follwed the CPU mode install and upon running the test script (or even when accessing the man page) I receive the errors in the attached screenshot. Is this simply because I didn't  run `conda install pytorch==1.13.1 torchvision==0.14.1 torchaudio==0.13.1 pytorch-cuda=11.6 -c pytorch -c nvidia`  or should I be worried about this for prediction ?

**Comment by housw** [comment]
Yes, you need to install these deep-learning libraries to use the model for sequence classification.
